[project]
name = "tetrapy"
version = "1.0.2"
description = "..."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.4.1",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "python-box[all]>=7.4.1",
    "rich>=13.0.0",
    "rioxarray>=0.19.0",
    "scipy>=1.15.3",
    "spectral>=0.25",
    "xarray>=2025.6.1",
]

[project.scripts]
tetrapy = "tetrapy.__main__:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
